-- ============================================================
-- Premium Petrol Radar — Advanced Data Science Schema Additions
-- Upgrade V2: Predictive Analytics & Usage Tracking
-- ============================================================

-- ── 1. Fuel Pricing History (Time-series) ─────────────────────
-- Tracks daily price fluctuations to build price elasticity models.
CREATE TABLE IF NOT EXISTS public.fuel_pricing_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id BIGINT REFERENCES public.fuel_stations(id) ON DELETE CASCADE,
  grade_name TEXT NOT NULL,
  price_per_litre NUMERIC(8,2) NOT NULL,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_price_history_time ON public.fuel_pricing_history(recorded_at);

-- ── 2. Regional Imports & Sales (Macro Data) ──────────────────
-- Tracks supply chain volume at a macro state/regional level.
CREATE TABLE IF NOT EXISTS public.fuel_imports_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region TEXT NOT NULL,
  fuel_type TEXT CHECK (fuel_type IN ('Petrol', 'Diesel', 'Aviation')),
  import_volume_kl NUMERIC(12,2) NOT NULL, -- in Kilolitres
  sales_volume_kl NUMERIC(12,2) NOT NULL,
  record_date DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_imports_sales_date ON public.fuel_imports_sales(record_date);
CREATE INDEX IF NOT EXISTS idx_imports_sales_region ON public.fuel_imports_sales(region);

-- ── 3. Granular Fuel Usage (Micro Data) ───────────────────────
-- Tracks precise consumption metrics categorized by grade and city.
CREATE TABLE IF NOT EXISTS public.regional_fuel_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT NOT NULL,
  grade_name TEXT NOT NULL,
  daily_consumption_litres BIGINT NOT NULL,
  record_date DATE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fuel_usage_city ON public.regional_fuel_usage(city);
CREATE INDEX IF NOT EXISTS idx_fuel_usage_date ON public.regional_fuel_usage(record_date);

-- ── 4. Edge Case Predictions (Model Outputs) ──────────────────
-- Stores output from predictive algorithms forecasting shortages.
CREATE TABLE IF NOT EXISTS public.supply_predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT NOT NULL,
  grade_name TEXT NOT NULL,
  shortage_probability NUMERIC(3,2) CHECK (shortage_probability BETWEEN 0 AND 1),
  predicted_exhaustion_date TIMESTAMPTZ,
  model_version TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_predictions_city ON public.supply_predictions(city);
CREATE INDEX IF NOT EXISTS idx_predictions_prob ON public.supply_predictions(shortage_probability);
