-- ============================================================
-- Premium Petrol Radar — Supabase Database Schema
-- PostgreSQL + PostGIS for spatial fuel station queries
-- ============================================================

-- ── 1. Enable PostGIS Extension ──────────────────────────────
CREATE EXTENSION IF NOT EXISTS postgis;

-- ── 2. Fuel Stations Table ───────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fuel_stations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  brand       TEXT NOT NULL CHECK (brand IN ('IndianOil', 'HPCL', 'BPCL', 'Shell', 'Nayara', 'Reliance', 'Other')),
  city        TEXT NOT NULL,
  state       TEXT NOT NULL DEFAULT '',
  lat         DOUBLE PRECISION NOT NULL,
  lng         DOUBLE PRECISION NOT NULL,
  location    GEOGRAPHY(POINT, 4326) NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Spatial index for proximity queries
CREATE INDEX IF NOT EXISTS idx_fuel_stations_location
  ON public.fuel_stations USING GIST (location);

-- B-tree indexes for filtering
CREATE INDEX IF NOT EXISTS idx_fuel_stations_brand  ON public.fuel_stations (brand);
CREATE INDEX IF NOT EXISTS idx_fuel_stations_city   ON public.fuel_stations (city);

-- ── 3. Fuel Grades Table (per-station grade availability) ────
CREATE TABLE IF NOT EXISTS public.fuel_grades (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id           BIGINT NOT NULL REFERENCES public.fuel_stations(id) ON DELETE CASCADE,
  grade_name           TEXT NOT NULL CHECK (grade_name IN ('XP100', 'Power100', 'Power99', 'Speed97', 'XP95', 'Power95', 'E20', 'E10', 'Standard')),
  ron_rating           INTEGER NOT NULL DEFAULT 87,
  ethanol_pct          NUMERIC(4,1) NOT NULL DEFAULT 20.0,
  price_per_litre      NUMERIC(8,2) NOT NULL,
  availability_status  TEXT NOT NULL DEFAULT 'Available' CHECK (availability_status IN ('Available', 'Limited Stock', 'Out of Stock', 'Just Reported', 'Unverified')),
  last_verified        TIMESTAMPTZ DEFAULT NOW(),
  verified_by          TEXT,
  created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fuel_grades_station   ON public.fuel_grades (station_id);
CREATE INDEX IF NOT EXISTS idx_fuel_grades_grade     ON public.fuel_grades (grade_name);
CREATE INDEX IF NOT EXISTS idx_fuel_grades_ron       ON public.fuel_grades (ron_rating);

-- ── 4. Community Reports Table ───────────────────────────────
CREATE TABLE IF NOT EXISTS public.community_reports (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id      BIGINT REFERENCES public.fuel_stations(id) ON DELETE SET NULL,
  user_id         UUID DEFAULT gen_random_uuid(),
  station_name    TEXT NOT NULL,
  brand           TEXT NOT NULL,
  grade_reported  TEXT NOT NULL,
  ron_rating      INTEGER NOT NULL DEFAULT 87,
  ethanol_pct     NUMERIC(4,1) NOT NULL DEFAULT 20.0,
  price_reported  NUMERIC(8,2),
  queue_wait_mins INTEGER DEFAULT 0,
  lat             DOUBLE PRECISION,
  lng             DOUBLE PRECISION,
  notes           TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_community_reports_created ON public.community_reports (created_at DESC);

-- ── 5. Daily Prices Table ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.daily_prices (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state         TEXT NOT NULL,
  city          TEXT NOT NULL,
  petrol_price  NUMERIC(8,2) NOT NULL,
  diesel_price  NUMERIC(8,2) NOT NULL,
  date          DATE NOT NULL DEFAULT CURRENT_DATE,
  source        TEXT DEFAULT 'manual',
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (state, city, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_prices_date ON public.daily_prices (date DESC);

-- ── 6. Row Level Security (RLS) Policies ─────────────────────
ALTER TABLE public.fuel_stations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_grades      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_prices     ENABLE ROW LEVEL SECURITY;

-- Public read access for all tables
CREATE POLICY "Public read fuel_stations"
  ON public.fuel_stations FOR SELECT
  USING (true);

CREATE POLICY "Public read fuel_grades"
  ON public.fuel_grades FOR SELECT
  USING (true);

CREATE POLICY "Public read community_reports"
  ON public.community_reports FOR SELECT
  USING (true);

CREATE POLICY "Public read daily_prices"
  ON public.daily_prices FOR SELECT
  USING (true);

-- Anyone can insert community reports (crowd-sourcing)
CREATE POLICY "Anyone can insert reports"
  ON public.community_reports FOR INSERT
  WITH CHECK (true);

-- ── 7. Spatial Query: Get Nearby Stations ────────────────────
CREATE OR REPLACE FUNCTION public.get_nearby_stations(
  user_lng DOUBLE PRECISION,
  user_lat DOUBLE PRECISION,
  radius_meters DOUBLE PRECISION DEFAULT 10000,
  fuel_filter TEXT DEFAULT NULL
)
RETURNS TABLE (
  station_id      BIGINT,
  station_name    TEXT,
  brand           TEXT,
  city            TEXT,
  state           TEXT,
  lat             DOUBLE PRECISION,
  lng             DOUBLE PRECISION,
  grade_name      TEXT,
  ron_rating      INTEGER,
  ethanol_pct     NUMERIC,
  price_per_litre NUMERIC,
  availability    TEXT,
  last_verified   TIMESTAMPTZ,
  distance_m      DOUBLE PRECISION
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    s.id            AS station_id,
    s.name          AS station_name,
    s.brand,
    s.city,
    s.state,
    s.lat,
    s.lng,
    g.grade_name,
    g.ron_rating,
    g.ethanol_pct,
    g.price_per_litre,
    g.availability_status AS availability,
    g.last_verified,
    ST_Distance(
      s.location,
      ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography
    ) AS distance_m
  FROM public.fuel_stations s
  JOIN public.fuel_grades g ON g.station_id = s.id
  WHERE ST_DWithin(
    s.location,
    ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography,
    radius_meters
  )
  AND (fuel_filter IS NULL OR g.grade_name = fuel_filter)
  ORDER BY distance_m ASC;
$$;

-- ── 8. Trigger: Auto-update updated_at ───────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_fuel_stations_updated
  BEFORE UPDATE ON public.fuel_stations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── 9. Auto-populate location from lat/lng ───────────────────
CREATE OR REPLACE FUNCTION populate_location()
RETURNS TRIGGER AS $$
BEGIN
  NEW.location = ST_SetSRID(ST_MakePoint(NEW.lng, NEW.lat), 4326)::geography;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_fuel_stations_location
  BEFORE INSERT OR UPDATE ON public.fuel_stations
  FOR EACH ROW EXECUTE FUNCTION populate_location();
